//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rozkladEntities2 : DbContext
    {
        public rozkladEntities2()
            : base("name=rozkladEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<flow> flows { get; set; }
        public virtual DbSet<group> groups { get; set; }
        public virtual DbSet<kafedra> kafedras { get; set; }
        public virtual DbSet<lecturer> lecturers { get; set; }
        public virtual DbSet<shchedule> shchedules { get; set; }
        public virtual DbSet<subject> subjects { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<audience> audiences { get; set; }
        public virtual DbSet<campu> campus { get; set; }
    }
}
